[package]
name = "ai_programs_todolist"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.0"
rusqlite = "0.26.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
